service: serverless-node-text-message-app

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    # Replace these environment variables with your Twilio and Google values
    TWILIO_ACCOUNT_SID: insert-your-key-here
    TWILIO_AUTH_TOKEN: insert-your-key-here
    TWILIO_PHONE_NUMBER: insert-your-key-here 
    GOOGLE_RECAPTCHA_TOKEN: insert-your-key-here

functions:
  validateRecaptchaSendSms:
    handler: handler.validateAndSend
    events:
      - http:
          path: api/sendSms
          method: post
          integration: lambda
          cors: true

plugins:
  - serverless-finch

custom:
  client:
    bucketName: enter-your-bucket-name-here

